version: '3.9'

services:
  postgres_db:
    image: postgres:15
    container_name: horoscope_postgres
    volumes:
      - ../horoscope_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "${DB_OUT_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      retries: 5

  web:
    build: .
    container_name: horoscope_app
    command: >
      bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      postgres_db:
        condition: service_healthy