# Generated by Django 4.1.7 on 2023-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zodiac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latin_name", models.CharField(max_length=15)),
                ("russian_name", models.CharField(max_length=15)),
            ],
        ),
    ]
