# Generated by Django 4.1.7 on 2023-03-02 17:15

from django.db import migrations
from django.core.management import call_command

from horoscope_project.settings import BASE_DIR
from horoscope_app.apps import HoroscopeAppConfig

fixture = f"{BASE_DIR}/horoscope_app/migrations/fixtures/dump_db.json"


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label=HoroscopeAppConfig.name)


class Migration(migrations.Migration):
    dependencies = [
        ("horoscope_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
