name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Compose
        uses: docker/compose-action@v2.2.1
        with:
          compose-file: docker-compose.yml

      - name: Run tests
        run: pytest
